version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: fashion_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # Express Backend Service
  backend:
    build: .
    container_name: fashion_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/fashionApp?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data: